services:
  - type: web
    name: ultimate-bet-money-management
    env: node
    plan: free
    buildCommand: npm ci --include=dev --legacy-peer-deps && npx vite build && ls -la dist/
    startCommand: npm run start:render
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18
      - key: NPM_CONFIG_LEGACY_PEER_DEPS
        value: true
    healthCheckPath: /health