services:
  - type: web
    name: ultimate-bet-money-management
    env: node
    plan: free
    buildCommand: npm ci --include=dev && npx vite build
    startCommand: node server.render.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18
    healthCheckPath: /health