services:
  - type: web
    name: ultimate-bet-money-management
    env: node
    plan: free
    buildCommand: npm ci --include=dev --legacy-peer-deps && npm run build
    startCommand: node server.render.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health
    disk:
      name: data
      mountPath: /data
      sizeGB: 1